### ISSUE TITLE
Install failing on AWS

### ISSUE THREAD

**Issue by dmittal77** [billabear/billabear#17]
### Discussed in https://github.com/billabear/billabear/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **dmittal77** April 15, 2024</sup>
Hi
Ran the docker on an AWS instance after adding stripe keys in the env file as documented. 
Accessed it at http://<public IP of AWS instance>
It got redirected to http://<IP>/install and it didn't load the page.
Here is the HTML for it. The assets /build/app.13dac4db.css and /build/app.099064ab.js are not available and there is a 404 error.

Anything to check / verify  - which can help resolve this?  Thank you

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <meta charset="UTF-8">
  | <title>BillaBear</title>
  | <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  | <link rel="manifest" href="/site.webmanifest">
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  | <link rel="stylesheet" href="/build/app.13dac4db.css">
  |  
  | <script src="/build/runtime.9a71ee5d.js" defer></script><script src="/build/app.099064ab.js" defer></script>
  | </head>
  | <body class="bg-gray-50 dark:bg-gray-900">
  | <div id="app"></div>
  | </body>
  | </html>
  |  

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>BillaBear</title>
        <link rel="apple-touch-icon" sizes="180x180" href="[/apple-touch-icon.png](http://IP/apple-touch-icon.png)">
        <link rel="icon" type="image/png" sizes="32x32" href="[/favicon-32x32.png](http://IP/favicon-32x32.png)">
        <link rel="icon" type="image/png" sizes="16x16" href="[/favicon-16x16.png](http://IP/favicon-16x16.png)">
        <link rel="manifest" href="[/site.webmanifest](http://IP/site.webmanifest)">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
                    <link rel="stylesheet" href="[/build/app.13dac4db.css](http://IP/build/app.13dac4db.css)">
        
                    <script src="[/build/runtime.9a71ee5d.js](http://IP/build/runtime.9a71ee5d.js)" defer></script><script src="[/build/app.099064ab.js](http://IP/build/app.099064ab.js)" defer></script>
            </head>
    <body class="bg-gray-50 dark:bg-gray-900">
        <div id="app"></div>
    </body>
</html></div>

**Comment by that-guy-iain** [comment]
Docker images have been updated. If you repull the docker images it will work now.

**Comment by dmittal77** [comment]
Thank you very much, Iain, it is working now!
